# Generated by Django 4.0.6 on 2022-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_area_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=1, upload_to='property/'),
            preserve_default=False,
        ),
    ]
