# Generated by Django 4.0.6 on 2022-08-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_category_category_name_alter_property_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('rate', 'rate'), ('sale', 'sale')], max_length=10),
        ),
    ]
